# Generated by Django 4.2 on 2023-04-28 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mathapi', '0003_pokeballs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='files/pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='UserPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_caught', models.DateTimeField(verbose_name='Time of capture')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mathapi.pokemon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pokemon', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LifetimePokeballs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier1', models.IntegerField(default=0)),
                ('tier2', models.IntegerField(default=0)),
                ('tier3', models.IntegerField(default=0)),
                ('tier4', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lf_pokeballs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LifetimeInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier1', models.IntegerField(default=0)),
                ('tier2', models.IntegerField(default=0)),
                ('tier3', models.IntegerField(default=0)),
                ('tier4', models.IntegerField(default=0)),
                ('passes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifetime_inventory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier1', models.IntegerField(default=0)),
                ('tier2', models.IntegerField(default=0)),
                ('tier3', models.IntegerField(default=0)),
                ('tier4', models.IntegerField(default=0)),
                ('passes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_inventory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
