# Generated by Django 4.2 on 2023-09-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathapi', '0007_question_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('ADD', 'Addition'), ('SUB', 'Subtraction'), ('ASUB', 'Addition and subtraction'), ('MULT', 'Multiplication'), ('DIV', 'Division'), ('EQ_A', 'Find answer to the equation'), ('EQ_M', 'Find missing value of the equation')], max_length=4)),
                ('hint', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='q_string',
            field=models.CharField(default='', max_length=128),
        ),
    ]
