# Generated by Django 4.2 on 2023-10-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathapi', '0009_delete_questiontype_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ans_method',
            field=models.CharField(choices=[('TYPE', 'Type answer and press enter'), ('SELC', 'Select the correct answer')], default='TYPE', max_length=4),
        ),
        migrations.AddField(
            model_name='question',
            name='other_answers',
            field=models.JSONField(default={'ans': []}),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('ADD', 'Addition'), ('SUB', 'Subtraction'), ('ASUB', 'Addition and subtraction'), ('MULT', 'Multiplication'), ('DIV', 'Division'), ('EQ_A', 'Find answer to the equation'), ('EQ_M', 'Find missing value of the equation'), ('MCQ', 'Select correct answer')], default='EQ_A', max_length=4),
        ),
    ]
