# Generated by Django 4.2 on 2023-10-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathapi', '0010_question_ans_method_question_other_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_string',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
